# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift

use_frameworks!

target 'Wolf Beacon' do

pod 'FontAwesomeKit', '~> 2.2.0'
pod 'SVProgressHUD'
pod 'AFNetworking'
pod 'DZNEmptyDataSet'
pod 'TextFieldEffects'
pod 'IQKeyboardManagerSwift'
pod 'SDWebImage'
pod 'ChameleonFramework/Swift'
pod 'RealmSwift'

end

target 'Wolf BeaconTests' do

end

target 'Wolf BeaconUITests' do

end

