# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wolf Beacon' do
	# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
	use_frameworks!

	pod 'SVProgressHUD'
	pod 'AFNetworking'
	pod 'DZNEmptyDataSet'
	pod 'SDWebImage'
	pod 'KWTransition'
	pod 'Lock'
	pod 'Auth0', '~> 1.4'
	pod 'DZNEmptyDataSet'
	pod 'SimpleKeychain'
	pod 'IQDropDownTextField'
	pod 'VLRTextField'
	pod 'IQKeyboardManager'
	pod 'UITextView+Placeholder'

	# Pods for Wolf Beacon

end
